### ISSUE TITLE
Add TypeScript support 

### ISSUE THREAD

**Issue by regalius** [tokopedia/treats#2]
**Is your feature request related to a problem? Please describe.**
Typescript support

**Describe the solution you'd like**
Using ts-loader

**Comment by martinock** [comment]
Just do some finishing on unit testing. Please review and track the progress on #7

**Comment by regalius** [comment]
Merged, Treats officially supports TypeScript. 🎉 🎉 🎉 

Thanks for the great work @martinock 

Closing this issue for now
