### ISSUE TITLE
Undefined when loading async bundle

### ISSUE THREAD

**Issue by regalius** [tokopedia/treats#4]
**Describe the bug**
Undefined and loading... sometimes shown when loading async bundles on SSR

**To Reproduce**
Intermittently happens on some builds

**Expected behavior**
SSR renders the page

**Additional context**
Leads:
Node modules install sometimes doing weird behavior, this caused several npm module to be installed inside `node_modules/treats/node_modules` rather than `node_modules/` directly, this can breaks some library like `react-universal-component`

**Comment by martinock** [comment]
This issue happened when we don't provide customRenderers in our server. When no customRenderers is provided, result was always undefined, therefore the SSR result is undefined.
Already create a PR on this #10 . Please review

**Comment by regalius** [comment]
Seems resolved, closing this for now, will reopen if found the same issues again
